### ISSUE TITLE
mapVariable allows null values when value type is not nullable

### ISSUE THREAD

**Issue by rvinzent** [holunda-io/camunda-bpm-data#164]
### Steps to reproduce

* camunda-bpm-data version: 1.2.3
* Camunda BPM version: 7.16.0-ee
* JDK version:  11 (Kotlin 1.5.20)
* Operating system: MacOs
* Complete executable reproducer: (e.g. GitHub Repo): the problem is simple enough...
* Steps: (what exactly are you doing with the above reproducer?)
    - run the below test

```kotlin
object TestVariables {
    val noNullValues: VariableFactory<Map<String, Any>> = mapVariable("noNullValues")
}

class TestIssue {
    @Test
    fun `test null values throw WrongVariableTypeException` {
        val data = mapOf("first" to 1, "second" to null)
        val mockExecution = delegateExecutionFake().withVariable("noNullValues", data)
        assertThrows<WrongVariableTypeException> {
            TestVariables.notNullValues.from(mockExecution).get()
        }
    }
}
```

### Expected behaviour
- expect `WrongVariableTypeException` to be thrown
- using a Kotlin extension leads me to believe the types of Map keys and values is correct, even in Kotlin

### Actual behaviour
- null value is allowed, violating Kotlin's null safety guarantees

----

I cannot work around this problem with a nullable type because type bounds of `mapVariable` don't allow a nullable type, so changing my value type to `Any?` is not allowed by the compiler.

```kotlin
inline fun <reified K : Any, reified V : Any> mapVariable(name: String): VariableFactory<Map<K, V>> =
    MapVariableFactory(name, K::class.java, V::class.java)
```

This issue makes using map variables dangerous as the values are all implicitly nullable even though I can't use an appropriate nullable type. Even knowing this, the IDE still throws warnings everywhere that I am checking for `null` on what should be a non-nullable value.

**Comment by zambrovski** [comment]
I'll change the signatures (for Map, List and Set) but will still provide the versions of non-nullable collections.
