### ISSUE TITLE
Handle access to non-existing variable correctly

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-data#18]
If using `get()` or `getOptional()` in adapters evaluate the `null` value of the variable, which is wrong, since Camunda would through an exception is the variable is not there.

**Comment by zambrovski** [comment]
Couldn't reproduce it in test so far

**Comment by christian-maschmann** [comment]
After looking into the Camunda-implementation, it's correct to expect a null-value in case of non-existing variables.
