### ISSUE TITLE
Java 8 - Support

### ISSUE THREAD

**Issue by janhuddel** [holunda-io/camunda-bpm-data#273]
### Scenario

* camunda-bpm-data version: 1.2.6
* Camunda BPM version: 7.16 / 7.17
* Description of your use case: 

We would like to use the library in our process application projects. However, we are currently still forced to use Java 8.
Quickly I could identify only one place in the code which is not Java 8 compatible: `CamundaBpmDataTest.java:321`

But this can be easily corrected by simply using the concrete type here (ProcessInstanceWithVariables). After correcting this and setting the java.version in the pom.xml to 1.8, I was able to use the library in my project.

Are there any other reasons which require the use of Java > 8?

### Current Behaviour
No Java 8-Support

### Wanted Behaviour
Java 8-Support

### Possible Workarounds
Fork the project and compile with Java 8.

**Comment by zambrovski** [comment]
Hi,

sorry, for not responding to it. I'll have a look on this.
In general, JDK 1.8 is deprecated and even 11 is not the current LTS.
I think for the current state - your workaround of cloning and re-compiling with JDK8 is ok. 

In the same time - we rely on camunda-bpm-mockito and this is JDK 11 (at least), so currently no backport is possible. It is not only about the `camunda-bpm-data-test` module, but alos about the test of the core part itself. For example: `extension/core/src/test/java/io/holunda/camunda/bpm/data/reader/VariableScopeReaderTest.java` is using `DelegateExecutionFake` which is a part of camunda-bpm-mockito...


P.S. we are planing a larger refactoring of the library and possibly the test part will go away (and will be part of Camunda BPM Mockito)... 

Cheers,

Simon
