### ISSUE TITLE
VariableFactories for new Java Time API

### ISSUE THREAD

**Issue by cwiejack** [holunda-io/camunda-bpm-data#316]
Hi,

are you interested in default methods for new Java Time API (Instant, LocalDate, LocalDateTime) for the VariableFactory?
Similar to uuidVariable(...) and dateVariable(...) it could look like:

instantVariable(...)
localDateVariable(...)
localDateTimeVariable(...)

Regards
Christian

**Comment by zambrovski** [comment]
Hi, 

I thought about it already. There is a custom factory in place and Camunda can‘t handle it anyhow. So the difference to UUID is its special serialization - a string which can‘t be delivered by the object mapper. By Java Time API dates you can declare a custom factory of the temporal type and configure Jackson OM to serialize it correctly.

So in the end I don‘t see any real need for this. We don‘t want to implement all types by specific factories.

What is the driving force for you to create one? Is there any use case you can’t cover with a custom factory?

Cheers,

Simon

**Comment by cwiejack** [comment]
Hi Simon,

no real need. Just came to my mind the moment i fixed the uuidVariable documentation a couple of minutes ago.  And I thought I could ask. So this could be closed then ;)

Regards
Christian
