### ISSUE TITLE
Permit operator-like usage of get functions

### ISSUE THREAD

**Issue by lbilger** [holunda-io/camunda-bpm-data#395]
### Scenario

* camunda-bpm-data version: 1.4.0
* Camunda BPM version: 7.20.0
* Description of your use case: (detailed description or executable reproducer, e.g. GitHub repo)

### Current Behaviour

When using the Java implementation from Kotlin, one could use the `[]` operator instead of `get`, e.g. `reader[MY_VARIABLE]`. This is no longer possible in the Kotlin implementation.

### Wanted Behaviour

`get` functions should be marked as `operator fun` so they can be used this way.

### Possible Workarounds

This is just for convenience / compatibility with previous version. Workaround is to call `get` explicitly.

**Comment by zambrovski** [comment]
I understand your wish, but struggling with the implementation. Do you have time to provide a PR?
