### ISSUE TITLE
VariableBuilders do not follow the Builder pattern.

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-data#49]
I noticed that the VariableBuilders I can access through `CamundaBpmData.builder(xxx)` are merely fluent setters.
They do not create a new instance everytime I call `build()`, they modify the variable source passed  while I use them.

While when working with VariableMap and VariableScope this might just be confusing, when working with tasks or executions, this leads to many single "set" calls on the api and leaves the system modified even when `build()`is not called.

Since the convenient fluent setting of multiple variables on the same adapter is the real goal behind the builder() idea, I would vote for renaming them to "writer" (analogue to the readers in #47 ).

**Comment by zambrovski** [comment]
Please refactor the methods to `writer` and update the documentation and changelog.
